### ISSUE TITLE
tflint deep IAM policy

### ISSUE THREAD

**Issue by ian-bartholomew** [terraform-linters/tflint-ruleset-aws#33]
Hello, we want to run this in CI, and be able to also run the deep inspection, but its not clear what kind of IAM permissions are needed.  We want to run this in CI, and grant it the least privileged IAM policy.

Thanks!

**Comment by rquadling** [comment]
Hi.

Please can we have a complete list of required permissions for tflint.

We have a specific user that is used to plan and apply using terraform and all is working there.

We've introduced tflint into our process and we now requiring additional access...
```
Failed to check ruleset. An error occurred:

Error: Failed to check `aws_instance_invalid_key_name` rule: An error occurred while invoking DescribeKeyPairs; UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: *********
```

amongst other things.

As it stands, the user used to deploy the terraform plan does NOT require these permissions and so we would not have granted that.

If this is something that is available in code (but not documented), then potentially the list of calls being made by the ruleset could be extracted and the logged. That would certainly be a start?

Some sort of auto-discovery?

**Comment by wata727** [comment]
Ah, that makes sense. It's easy to document the list of required permissions because just check the implementation under the [`api`](https://github.com/terraform-linters/tflint-ruleset-aws/tree/8047cf5d9d74e1175e1fb2481853577f5ca6dd1e/rules/api) directory.

I haven't been able to work on this for other work, but I'd be happy to review it if you open a PR.
